version: "3.8"
services: 
    mysqldb:
      image: "mysql:8.0"
      # restart: always
      ports:
        - 3307:3306
      environment:
        MYSQL_DATABASE: ankushkumar
        MYSQL_USER: ankush
        MYSQL_PASSWORD: atylbvc_+90B
        MYSQL_ROOT_PASSWORD: atylbvc_+90B
      networks:
        - backend
      # volumes:
      #   - ./ankushkumar_user.sql:/docker-entrypoint-initdb.d/ankushkumar_user.sql
    server: 
      build: .
      # restart: always
      ports: 
        - 8080:8080
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3307/ankushkumar  # Use the correct service name and port
        SPRING_DATASOURCE_USERNAME: ankush
        SPRING_DATASOURCE_PASSWORD: atylbvc_+90B
      depends_on:
        - mysqldb
      networks:
        - backend

networks:
  backend:
    driver: bridge